/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.idcard;
import invoice1.*;
import aa.*;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Mayank Nakhate
 */

public class newcard extends javax.swing.JFrame {
    String path2 = null;
 public newcard() {
        initComponents();
        p1.setBackground(Color.white);
        tin.setBorder(null);
        tin.setEditable(false);
        tname.setEditable(false);
        tbg.setBorder(null);
        tdoa.setBorder(null);
        tdob.setBorder(null);
        tcn.setBorder(null);
        tfa.setBorder(null);
        tname.setBorder(null);
        temail.setBorder(null);
        temail.setEditable(false);
        
        try
        {
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/id_card", "root", "");
            PreparedStatement pst = con.prepareStatement("select * from cust_details where id=(select max(id) from cust_details) ");
            ResultSet r = pst.executeQuery();
            while (r.next())
            {
                int id = r.getInt("id");
                tfa.setText(r.getString("address"));
                tname.setText(r.getString("name"));
                tcn.setText(r.getString("phone"));
                tin.setText(r.getString("id"));
                temail.setText(r.getString("email"));
                tdoa.setText(r.getString("doa"));
                tdob.setText(r.getString("dob"));
                tbg.setText(r.getString("blood_group"));
                Blob image = r.getBlob("photo");
                String imagename=r.getString("image");
                String path = "D:\\Project Images\\"+imagename;
                BufferedImage bi = ImageIO.read(new File(path));
                Image img = bi.getScaledInstance(140, 169, Image.SCALE_SMOOTH);
                ImageIcon icon = new ImageIcon(img);
                lbii.setIcon(icon);
                               
                
            }
            
        }
        catch(Exception we)
        {
            System.out.println("Ex:"+we);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        p1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lb1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tin = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        temail = new javax.swing.JTextField();
        tname = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        tcn = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tbg = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tdoa = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tdob = new javax.swing.JTextField();
        tfa = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        lbii = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 21)); // NOI18N
        jButton5.setText("Home");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 21)); // NOI18N
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 21)); // NOI18N
        jButton2.setText("Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        p1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        p1.setPreferredSize(new java.awt.Dimension(250, 882));
        p1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Identity Card");
        p1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 150, 60));

        lb1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/invoice1/pngwing.com (21).png"))); // NOI18N
        p1.add(lb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 670, 90, 80));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Authorized Signatory");
        p1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 740, 170, 50));

        tin.setEditable(false);
        tin.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        tin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinActionPerformed(evt);
            }
        });
        p1.add(tin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 270, 40));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("ID No.          :");
        p1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 110, 40));

        temail.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        temail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temailActionPerformed(evt);
            }
        });
        p1.add(temail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 270, 40));

        tname.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        p1.add(tname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 300, 70));
        p1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 2, 30, 830));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Blood Group   :");
        p1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, 120, 40));

        tcn.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        tcn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcnActionPerformed(evt);
            }
        });
        p1.add(tcn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 270, 40));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Contact No.   :");
        p1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 110, 40));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("Email            :");
        p1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 110, 40));

        tbg.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        tbg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbgActionPerformed(evt);
            }
        });
        p1.add(tbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 570, 270, 40));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("D.O.A.         :");
        p1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 110, 40));

        tdoa.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        tdoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdoaActionPerformed(evt);
            }
        });
        p1.add(tdoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 270, 40));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("D.O.B.         :");
        p1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 110, 40));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setText("Address        :");
        p1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, 110, 40));

        tdob.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        tdob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdobActionPerformed(evt);
            }
        });
        p1.add(tdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 270, 40));

        tfa.setColumns(20);
        tfa.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        tfa.setRows(5);
        p1.add(tfa, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 620, 270, 80));

        lbii.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 255)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbii, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbii, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        p1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 140, 170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton5)
                    .addComponent(jButton4)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        printRecord(p1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Invoice ac=new Invoice();
            ac.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tdobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdobActionPerformed

    private void tdoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdoaActionPerformed

    private void tbgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbgActionPerformed

    private void tcnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcnActionPerformed

    private void temailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temailActionPerformed

    private void tinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newcard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newcard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newcard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newcard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newcard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lbii;
    private javax.swing.JPanel p1;
    private javax.swing.JTextField tbg;
    private javax.swing.JTextField tcn;
    private javax.swing.JTextField tdoa;
    private javax.swing.JTextField tdob;
    private javax.swing.JTextField temail;
    private javax.swing.JTextArea tfa;
    private javax.swing.JTextField tin;
    private javax.swing.JTextField tname;
    // End of variables declaration//GEN-END:variables
public void printRecord(JPanel Panel)
{
    PrinterJob printerJob = PrinterJob.getPrinterJob();
    printerJob.setPrintable(new Printable() {

        @Override
        public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException 
        {
           if(pageIndex > 0){
               return Printable.NO_SUCH_PAGE;
           }
           Graphics2D graphics2D = (Graphics2D)graphics;
           graphics2D.scale(0.47, 0.47);
           graphics2D.translate(pageFormat.getImageableX()*2, pageFormat.getImageableY()*2);
           p1.paint(graphics2D);
           return Printable.PAGE_EXISTS;
        }
    });
    boolean returningResult = printerJob.printDialog();
    if(returningResult){
        try{
            printerJob.print();
        }
        catch(PrinterException printerException)
                {
            JOptionPane.showMessageDialog(this, "Print Error : "+ printerException.getMessage());
        }
    }
}
}

